### ISSUE TITLE
And glfw3 and glew

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/robotology-additional-dependencies#2]
I think this would be nice addition to the `robotology-additional-dependencies` installers. They are small dependency-less libraries that are used by both Oculus support in YARP and by `superimpose-mesh-lib` .
cc @claudiofantacci @GiulioRomualdi

**Comment by traversaro** [comment]
Fixed by 58f8da7. The new installers are available at https://github.com/robotology-playground/robotology-additional-dependencies/releases/tag/v0.2.0 .

**Comment by claudiofantacci** [comment]
Great 🚀 

PS: there is an extra ` in the winpcap name in the release 😉

**Comment by traversaro** [comment]
Fixed, thanks!

**Comment by GiulioRomualdi** [comment]
@kouroshD, this simplify the windows setup!

**Comment by kouroshD** [comment]
Yes, it is very nice. I suggest, we add to the documentation of the [walking-teleoperation](https://github.com/robotology/walking-teleoperation).
